// Human-readable display labels for ZMK key codes.
// Maps ZMK #define names (and their aliases) to short labels for rendering on key caps.
// Source: https://github.com/zmkfirmware/zmk/blob/main/app/include/dt-bindings/zmk/keys.h

const ZMK_KEY_LABELS = {
  // Letters (already readable, but include for completeness)
  // A–Z are fine as-is

  // Numbers — [primary, shifted] for dual-legend keycap display
  NUMBER_1: ["1", "!"], N1: ["1", "!"],
  NUMBER_2: ["2", "@"], N2: ["2", "@"],
  NUMBER_3: ["3", "#"], N3: ["3", "#"],
  NUMBER_4: ["4", "$"], N4: ["4", "$"],
  NUMBER_5: ["5", "%"], N5: ["5", "%"],
  NUMBER_6: ["6", "^"], N6: ["6", "^"],
  NUMBER_7: ["7", "&"], N7: ["7", "&"],
  NUMBER_8: ["8", "*"], N8: ["8", "*"],
  NUMBER_9: ["9", "("], N9: ["9", "("],
  NUMBER_0: ["0", ")"], N0: ["0", ")"],

  // Shifted number symbols (standalone — when used directly via LS())
  EXCLAMATION: "!", EXCL: "!",
  AT_SIGN: "@", AT: "@",
  HASH: "#", POUND: "#",
  DOLLAR: "$", DLLR: "$",
  PERCENT: "%", PRCNT: "%",
  CARET: "^",
  AMPERSAND: "&", AMPS: "&",
  ASTERISK: "*", ASTRK: "*", STAR: "*",
  LEFT_PARENTHESIS: "(", LPAR: "(",
  RIGHT_PARENTHESIS: ")", RPAR: ")",

  // Whitespace / control
  RETURN: "Enter", ENTER: "Enter", RET: "Enter",
  ESCAPE: "Esc", ESC: "Esc",
  BACKSPACE: "Bksp", BSPC: "Bksp",
  TAB: "Tab",
  SPACE: "Space",
  DELETE: "Del", DEL: "Del",
  INSERT: "Ins", INS: "Ins",

  // Punctuation — dual-legend [primary, shifted] where applicable
  MINUS: ["-", "_"],
  UNDERSCORE: "_", UNDER: "_",
  EQUAL: ["=", "+"],
  PLUS: "+",
  LEFT_BRACKET: ["[", "{"], LBKT: ["[", "{"],
  RIGHT_BRACKET: ["]", "}"], RBKT: ["]", "}"],
  LEFT_BRACE: "{", LBRC: "{",
  RIGHT_BRACE: "}", RBRC: "}",
  BACKSLASH: ["\\", "|"], BSLH: ["\\", "|"],
  PIPE: "|",
  SEMICOLON: [";", ":"], SEMI: [";", ":"],
  COLON: ":",
  SINGLE_QUOTE: ["'", '"'], SQT: ["'", '"'], APOSTROPHE: ["'", '"'], APOS: ["'", '"'],
  DOUBLE_QUOTES: '"', DQT: '"',
  GRAVE: ["`", "~"],
  TILDE: "~",
  COMMA: [",", "<"],
  PERIOD: [".", ">"], DOT: [".", ">"],
  SLASH: ["/", "?"], FSLH: ["/", "?"],
  QUESTION: "?", QMARK: "?",
  LESS_THAN: "<", LT: "<",
  GREATER_THAN: ">", GT: ">",
  NON_US_HASH: "#", NUHS: "#",
  NON_US_BACKSLASH: "\\", NON_US_BSLH: "\\", NUBS: "\\",

  // Navigation
  HOME: "Home",
  END: "End",
  PAGE_UP: "PgUp", PG_UP: "PgUp",
  PAGE_DOWN: "PgDn", PG_DN: "PgDn",
  RIGHT_ARROW: "Right", RIGHT: "Right",
  LEFT_ARROW: "Left", LEFT: "Left",
  DOWN_ARROW: "Down", DOWN: "Down",
  UP_ARROW: "Up", UP: "Up",

  // Modifiers
  LEFT_CONTROL: "L Ctrl", LCTRL: "L Ctrl",
  LEFT_SHIFT: "L Shift", LSHIFT: "L Shift", LSHFT: "L Shift",
  LEFT_ALT: "L Alt", LALT: "L Alt",
  LEFT_GUI: "L Cmd", LGUI: "L Cmd", LEFT_WIN: "L Win", LWIN: "L Win",
  LEFT_COMMAND: "L Cmd", LCMD: "L Cmd", LEFT_META: "L Meta", LMETA: "L Meta",
  RIGHT_CONTROL: "R Ctrl", RCTRL: "R Ctrl",
  RIGHT_SHIFT: "R Shift", RSHIFT: "R Shift", RSHFT: "R Shift",
  RIGHT_ALT: "R Alt", RALT: "R Alt",
  RIGHT_GUI: "R Cmd", RGUI: "R Cmd", RIGHT_WIN: "R Win", RWIN: "R Win",
  RIGHT_COMMAND: "R Cmd", RCMD: "R Cmd", RIGHT_META: "R Meta", RMETA: "R Meta",

  // Lock keys
  CAPSLOCK: "Caps", CAPS: "Caps", CLCK: "Caps",
  SCROLLLOCK: "ScrLk", SLCK: "ScrLk",
  PRINTSCREEN: "PrtSc", PSCRN: "PrtSc",
  PAUSE_BREAK: "Pause",

  // Function keys (already short, but normalize)
  F1: "F1", F2: "F2", F3: "F3", F4: "F4", F5: "F5", F6: "F6",
  F7: "F7", F8: "F8", F9: "F9", F10: "F10", F11: "F11", F12: "F12",
  F13: "F13", F14: "F14", F15: "F15", F16: "F16", F17: "F17", F18: "F18",
  F19: "F19", F20: "F20", F21: "F21", F22: "F22", F23: "F23", F24: "F24",

  // Keypad
  KP_NUMLOCK: "NumLk", KP_NUM: "NumLk", KP_NLCK: "NumLk",
  KP_DIVIDE: "KP /", KP_SLASH: "KP /",
  KP_MULTIPLY: "KP *", KP_ASTERISK: "KP *",
  KP_MINUS: "KP -", KP_SUBTRACT: "KP -",
  KP_PLUS: "KP +",
  KP_ENTER: "KP Ent",
  KP_NUMBER_0: "KP 0", KP_N0: "KP 0",
  KP_NUMBER_1: "KP 1", KP_N1: "KP 1",
  KP_NUMBER_2: "KP 2", KP_N2: "KP 2",
  KP_NUMBER_3: "KP 3", KP_N3: "KP 3",
  KP_NUMBER_4: "KP 4", KP_N4: "KP 4",
  KP_NUMBER_5: "KP 5", KP_N5: "KP 5",
  KP_NUMBER_6: "KP 6", KP_N6: "KP 6",
  KP_NUMBER_7: "KP 7", KP_N7: "KP 7",
  KP_NUMBER_8: "KP 8", KP_N8: "KP 8",
  KP_NUMBER_9: "KP 9", KP_N9: "KP 9",
  KP_DOT: "KP .", KP_EQUAL: "KP =", KP_COMMA: "KP ,",
  KP_LEFT_PARENTHESIS: "KP (", KP_LPAR: "KP (",
  KP_RIGHT_PARENTHESIS: "KP )", KP_RPAR: "KP )",
  KP_CLEAR: "KP Clr",

  // System
  SYSTEM_POWER: "Power", SYS_PWR: "Power",
  SYSTEM_SLEEP: "Sleep", SYS_SLEEP: "Sleep",
  SYSTEM_WAKE_UP: "Wake", SYS_WAKE: "Wake",
  K_APPLICATION: "Menu", K_APP: "Menu", K_CONTEXT_MENU: "Menu", K_CMENU: "Menu",
  K_POWER: "Power", K_PWR: "Power",

  // Keyboard utility
  K_EXECUTE: "Exec", K_EXEC: "Exec",
  K_HELP: "Help",
  K_MENU: "Menu",
  K_SELECT: "Select",
  K_STOP: "Stop",
  K_AGAIN: "Again", K_REDO: "Redo",
  K_UNDO: "Undo",
  K_CUT: "Cut",
  K_COPY: "Copy",
  K_PASTE: "Paste",
  K_FIND: "Find",
  K_MUTE: "Mute",
  K_VOLUME_UP: "Vol+", K_VOL_UP: "Vol+",
  K_VOLUME_DOWN: "Vol-", K_VOL_DN: "Vol-",
  K_PLAY_PAUSE: "Play", K_PP: "Play",
  K_STOP2: "Stop",
  K_PREVIOUS: "Prev", K_PREV: "Prev",
  K_NEXT: "Next",
  K_EJECT: "Eject",
  K_LOCK: "Lock", K_SCREENSAVER: "Lock", K_COFFEE: "Lock",
  K_SCROLL_UP: "Scr Up", K_SCROLL_DOWN: "Scr Dn",
  K_SLEEP: "Sleep",
  K_CALCULATOR: "Calc", K_CALC: "Calc",
  K_REFRESH: "Refresh",
  K_BACK: "Back",
  K_FORWARD: "Fwd",

  // Consumer media/system
  C_POWER: "Power", C_PWR: "Power",
  C_RESET: "Reset",
  C_SLEEP: "Sleep",
  C_SLEEP_MODE: "Sleep",
  C_MUTE: "Mute",
  C_VOLUME_UP: "Vol+", C_VOL_UP: "Vol+",
  C_VOLUME_DOWN: "Vol-", C_VOL_DN: "Vol-",
  C_PLAY_PAUSE: "Play", C_PP: "Play",
  C_PLAY: "Play",
  C_PAUSE: "Pause",
  C_STOP: "Stop",
  C_RECORD: "Rec", C_REC: "Rec",
  C_FAST_FORWARD: "FF", C_FF: "FF",
  C_REWIND: "Rew", C_RW: "Rew",
  C_NEXT: "Next",
  C_PREVIOUS: "Prev", C_PREV: "Prev",
  C_EJECT: "Eject",
  C_RANDOM_PLAY: "Shuffle", C_SHUFFLE: "Shuffle",
  C_REPEAT: "Repeat",
  C_STOP_EJECT: "Stop/Ej",
  C_VOICE_COMMAND: "Voice",
  C_BASS_BOOST: "Bass+",

  // Brightness
  C_BRIGHTNESS_INC: "Bri+", C_BRI_INC: "Bri+", C_BRI_UP: "Bri+",
  C_BRIGHTNESS_DEC: "Bri-", C_BRI_DEC: "Bri-", C_BRI_DN: "Bri-",
  C_BACKLIGHT_TOGGLE: "BL Tog", C_BKLT_TOG: "BL Tog",
  C_BRIGHTNESS_MINIMUM: "Bri Min", C_BRI_MIN: "Bri Min",
  C_BRIGHTNESS_MAXIMUM: "Bri Max", C_BRI_MAX: "Bri Max",
  C_BRIGHTNESS_AUTO: "Bri Auto", C_BRI_AUTO: "Bri Auto",

  // Consumer channel/media select
  C_CHANNEL_INC: "Ch+", C_CHAN_INC: "Ch+",
  C_CHANNEL_DEC: "Ch-", C_CHAN_DEC: "Ch-",

  // Application launch
  C_AL_CALCULATOR: "Calc", C_AL_CALC: "Calc",
  C_AL_WWW: "Browser", C_AL_MY_COMPUTER: "My PC",
  C_AL_EMAIL: "Email", C_AL_MAIL: "Email",
  C_AL_LOCK: "Lock", C_AL_SCREENSAVER: "Lock", C_AL_COFFEE: "Lock",
  C_AL_FILE_BROWSER: "Files", C_AL_FILES: "Files",
  C_AL_AUDIO_BROWSER: "Music", C_AL_AUDIO: "Music", C_AL_MUSIC: "Music",
  C_AL_MOVIE_BROWSER: "Movies", C_AL_MOVIES: "Movies",
  C_AL_CALENDAR: "Calendar", C_AL_CAL: "Calendar",
  C_AL_CONTACTS: "Contacts", C_AL_ADDRESS_BOOK: "Contacts",
  C_AL_CONTROL_PANEL: "Ctrl Panel",
  C_AL_HELP: "Help",
  C_AL_DOCUMENTS: "Docs", C_AL_DOCS: "Docs",
  C_AL_WORD: "Word",
  C_AL_SPREADSHEET: "Sheet", C_AL_SHEET: "Sheet",
  C_AL_PRESENTATION: "Slides",
  C_AL_NETWORK_CHAT: "Chat", C_AL_CHAT: "Chat",
  C_AL_LOGOFF: "Logoff",
  C_AL_NEWS: "News",
  C_AL_INSTANT_MESSAGING: "IM", C_AL_IM: "IM",

  // Application control
  C_AC_NEW: "New",
  C_AC_OPEN: "Open",
  C_AC_CLOSE: "Close",
  C_AC_EXIT: "Exit",
  C_AC_SAVE: "Save",
  C_AC_PRINT: "Print",
  C_AC_UNDO: "Undo",
  C_AC_REDO: "Redo",
  C_AC_COPY: "Copy",
  C_AC_CUT: "Cut",
  C_AC_PASTE: "Paste",
  C_AC_FIND: "Find",
  C_AC_SEARCH: "Search",
  C_AC_HOME: "Home",
  C_AC_BACK: "Back",
  C_AC_FORWARD: "Fwd",
  C_AC_STOP: "Stop",
  C_AC_REFRESH: "Refresh",
  C_AC_BOOKMARKS: "Bookmarks", C_AC_FAVORITES: "Bookmarks",
  C_AC_ZOOM_IN: "Zoom+",
  C_AC_ZOOM_OUT: "Zoom-",
  C_AC_ZOOM: "Zoom",
  C_AC_SCROLL_UP: "Scr Up",
  C_AC_SCROLL_DOWN: "Scr Dn",
  C_AC_EDIT: "Edit",
  C_AC_CANCEL: "Cancel",
  C_AC_DEL: "Del",
  C_AC_REPLY: "Reply",
  C_AC_SEND: "Send",
  C_AC_DESKTOP_SHOW_ALL_WINDOWS: "Expose",
  C_AC_DESKTOP_SHOW_ALL_APPLICATIONS: "App Grid",
  C_AC_NEXT_KEYBOARD_LAYOUT_SELECT: "Globe", GLOBE: "Globe",

  // International
  INTERNATIONAL_1: "Int1", INT1: "Int1", INT_RO: "Int Ro",
  INTERNATIONAL_2: "Int2", INT2: "Int2", INT_KANA: "Kana",
  INTERNATIONAL_3: "Int3", INT3: "Int3", INT_YEN: "¥",
  INTERNATIONAL_4: "Int4", INT4: "Int4", INT_HENKAN: "変換",
  INTERNATIONAL_5: "Int5", INT5: "Int5", INT_MUHENKAN: "無変換",
  LANGUAGE_1: "Lang1", LANG1: "Lang1", LANG_HANGEUL: "한글",
  LANGUAGE_2: "Lang2", LANG2: "Lang2", LANG_HANJA: "漢字",
};

export default ZMK_KEY_LABELS;
